12 documentar diagrama de atividades
UnBArqDsw2024-2/2024.2_G3_Aprender_Entrega_02 pull request #15
Opened 2024-11-29 02:43 UTC by M0tt1nh4

## Descrição

Issue #12 (Documentar diagrama de atividades)

## Checklist

[x] Introdução
[x] Imagem do Diagrama
[x] Referências

2024-11-29 17:48 UTC, giovanniacg reviewed
No Diagrama de Atividades o usuário também pode responder questões individuais, não necessáriamente via simulado.

2024-11-29 17:52 UTC, giovanniacg requested changes
Ficou muito bom, falta apenas resolver a questão de um paralelismo no fluxo

2024-11-29 17:52 UTC, giovanniacg commented on docs/assets/diagrama-atividades.png
No fluxo do Aluno, ele também pode responder questões individuais, nem sempre são apenas pelo simulado.

2024-11-30 01:00 UTC, M0tt1nh4 commented on docs/assets/diagrama-atividades.png
Foi discutido em reunião que como o aluno pode configurar o seu simulado, ele poderia selecionar a matéria que desejar dentro do simulado, além de seu tempo, por isso dentro da situação de questões individuais, ele poderia selecionar uma matéria específica e com o tempo ilimitado para realizá-las.

2024-11-30 01:14 UTC, joao-artl approved these changes

2024-11-30 02:07 UTC, giovanniacg commented on docs/assets/diagrama-atividades.png
Realmente, faz mais sentido. Perfeito!

2024-11-30 02:07 UTC, giovanniacg approved these changes

2024-11-30 02:10 UTC, merged